name: Draft PR Workflow
on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  draft:
    runs-on: self-hosted
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              draft: true
            })

            console.log('Update Response:', JSON.stringify(response, null, 2))

            // Verify the change
            const verifyResponse = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            console.log('Verification Response:', JSON.stringify(verifyResponse, null, 2))
            
            if (!verifyResponse.data.draft) {
              throw new Error('Failed to convert PR to draft state')
            }

# name: Unit Tests:Python
# on:
#   workflow_call:

# jobs:
#   run:
#     name: Run tests
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3
#       - name: Unit Tests
#         run: echo "Running full test suite"