name: Draft PR Workflow
on:
  workflow_call:

jobs:
  draft:
    runs-on: self-hosted
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              draft: true
            })