# name: Unit Tests:Python

# on:
#   workflow_call:
#     inputs:
#       python_version:
#         type: string
#         default: "3.11.10"
#     secrets:
#       REPO_TOKEN:
#         required: true    # Add this secret

# jobs:
#   run:
#     name: Run tests
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4
#         name: Checkout Code Repository
#         with:
#           repository: ${{ github.event.repository.full_name }}
#           ref: ${{ github.event.pull_request.head.ref }}
          
#       - name: Checkout test scripts
#         uses: actions/checkout@v4
#         with:
#           # repository: luminolabs/infra-templates
#           repository: test-org-runner/infra-templates
#           ref: refs/heads/srujan/ci_cd
#           path: scripts
#           token: ${{ secrets.REPO_TOKEN }}  # Use the token here

#       - name: Run Test Script
#         env:
#           PYTHON_VERSION: ${{ inputs.python_version }}
#         run: |
#           chmod +x scripts/run_python_unittests.sh
#           scripts/run_python_unittests.sh

#       - name: Cleanup
#         if: always()
#         run: |
#           REPO_PATH=$(pwd)
#           cd ..
#           rm -rf $REPO_PATH


name: Unit Tests:Python

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        default: "3.11.10"
    secrets:
      PAT:
        required: true

jobs:
  run:
    name: Run tests
    runs-on: self-hosted
    steps:
      - name: Checkout unit tests script
        uses: actions/checkout@v4.2.2
        with:
          repository: test-org-runner/infra-templates
          ref: refs/heads/srujan/ci_cd
          path: gha_scripts    # Checkout outside main workspace
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            run_python_unittests.sh
          sparse-checkout-cone-mode: false

      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Test Script
        env:
          PYTHON_VERSION: ${{ inputs.python_version }}
        # working-directory: ${{ github.workspace }}/../scripts/  # Main workspace
        run: |
          chmod +x ./gha_scripts/run_python_unittests.sh
          ./gha_scripts/run_python_unittests.sh

      - name: Cleanup
        if: always()
        run: |
          rm -rf ${{ github.workspace }}