name: Unit Test:Python Workflow
on:
  workflow_call:

jobs:
  unit-test:
    if: contains(github.event.pull_request.labels.*.name, 'draft')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: echo "Running full test suite"
